Activity:
  Enable: 1
  Flare:
    Amplitude: 2500.0
    DurationDispersion: -1
    Enable: 1
    MeanDuration: -1
    MeanPeriod: 1
    Seed: -1
    UpDown: 0.1
  Seed: -1
  Sigma: 80.0
  Spot:
    Contrast:
    - 0.65
    Enable: 1
    Latitude:
    - 20.0
    Lifetime:
    - 15
    Longitude:
    - 0.0
    Modulation: 0.0
    MuSpot: 0.78
    MuStar: 0.59
    Radius:
    - 4.5
    Seed: -1
    TimeMax:
    - -1
    dOmega: 0.0
  Tau: 0.5
External:
  Enable: 0
  FilePath: examples/external_example.txt
Granulation:
  Enable: 1
  Seed: -1
  Type: 1
Instrument:
  GroupID:
  - 1
  - 2
  - 3
  - 4
  IntegrationTime: 21
  NCamera: 6
  RandomNoise:
    Enable: 1
    NSR: 73.0
    Type: PLATO_SIMU
  Sampling: 25
  Systematics:
    DriftLevel: any
    Enable: 1
    Seed: -1
    Table: systematics/PLATO_systematics_BOL_V2.npy
    Version: 2
  TimeShift: 6.25
Observation:
  Gaps:
    Enable: 1
    InterQuarterGapDuration: 3.0
    PeriodicGapCadence: 5.0
    PeriodicGapDuration: 20.0
    PeriodicGapJitter: 2.0
    PeriodicGapStep: 0.0
    RandomGapDuration: 0.0
    RandomGapStep: 0.0
    RandomGapTimeFraction: 0.5
    Seed: -1
  MasterSeed: 471242136
  QuarterDuration:
  - 90.0
  - 90.0
  - 90.0
Oscillations:
  DPI: -1
  Enable: 1
  Seed: -1
  SurfaceEffects: 1
  delta_nu: 135.0
  numax: 3090.0
  q: 0.0
Star:
  CoreRotationFreq: 0.0
  ES: ms
  ID: 1
  Inclination: 60.0
  Logg: 4.438
  Mag: 10.0
  ModelDir: models
  ModelName: grid_v0.1_ov0-plato.hdf5
  ModelType: grid
  SurfaceRotationPeriod: 8.0
  Teff: 5778.0
Transit:
  Enable: 0
  LimbDarkeningCoefficients:
  - 0.25
  - 0.75
  OrbitalAngle: 0.0
  OrbitalPeriod: 10.0
  PlanetRadius: 0.1
  PlanetSemiMajorAxis: 1.0
